Repository WOK-AT/WOKAT_CLIENT, pull requests merged in 2023-06, with the labels that each got.

#43 Feat/#38 리팩토링 및 디자인 요소 수정
  package.json
  src/assets/icons/location.svg
  src/components/WokatSEO.tsx
  src/components/common/Header.tsx
  src/components/common/ListFilter.tsx
  src/components/common/Modal.tsx
  src/components/detail/ShareModal.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
  src/components/list/FAB.tsx
  src/components/list/ListLanding.tsx
  src/components/list/OptionSelector.tsx
  src/components/list/PlaceList.tsx
  src/components/list/ReservationOption.tsx
  src/components/option/Calendar.tsx
  src/components/option/HeadCount.tsx
  src/context/OptionContext.tsx
  src/hooks/useDetail.ts
  src/hooks/useOption.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/detail/[id].tsx
  src/pages/index.tsx
  src/pages/list/index.tsx
  src/pages/list/option.tsx
  src/services/api/index.tsx
  src/services/detail/index.tsx
  src/services/detail/types.tsx
  src/services/index.ts
  src/services/list/index.tsx
  src/services/list/types.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: chore, feat

#48 Feat/#44 버그 수정 및 최적화
  src/assets/images/background.svg
  src/assets/images/main_background.svg
  src/components/common/Layout.tsx
  src/components/list/PlaceList.tsx
  src/components/search/SearchList.tsx
  src/components/search/SearchListItem.tsx
  src/data/subway_station_info.json
  src/hooks/useDetail.ts
  src/hooks/useInput.ts
  src/hooks/useStationSearch.ts
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: fix, chore, feat

#50 Feat/#49 공간 필터링 api 연결 및 UI 변동사항 반영
  src/assets/icons/info.svg
  src/components/common/ImageFallback.tsx
  src/components/common/ListFilter.tsx
  src/components/common/Loading.tsx
  src/components/common/Modal.tsx
  src/components/common/Navigation.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
  src/components/list/ListLanding.tsx
  src/components/list/Message.tsx
  src/components/list/OptionSelector.tsx
  src/components/list/PlaceList.tsx
  src/components/list/ReservationOption.tsx
  src/components/nearby-place/BottomSheet.tsx
  src/components/nearby-place/Map.tsx
  src/components/option/Calendar.tsx
  src/components/option/HeadCount.tsx
  src/context/NavigationContext.tsx
  src/context/OptionContext.tsx
  src/hooks/queries/useDetail.ts
  src/hooks/queries/usePlaceList.ts
  src/hooks/useBoolean.ts
  src/hooks/useFilter.ts
  src/hooks/useOption.tsx
  src/pages/detail/[id].tsx
  src/pages/list/index.tsx
  src/services/list/index.tsx
  src/services/list/types.tsx
  src/styles/globals.css
  src/utils/formatDate.ts
Labels: chore, feat

#51 온보딩 페이지 구현
  src/assets/images/onboarding_1.webp
  src/assets/images/onboarding_2.webp
  src/assets/images/onboarding_3.webp
  src/assets/images/onboarding_4.webp
  src/assets/images/onboarding_5.webp
  src/components/onboarding/Onboarding.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: feat

#55 Chore/#52 메인뷰 백그라운드 이미지 하단 여백 조정
  src/components/common/Layout.tsx
  src/pages/index.tsx
Labels: chore

#59 데이터 없는 리스트 페이지 구현
  src/assets/images/noResult.webp
  src/components/list/PlaceList.tsx
  src/components/nearby-place/BottomSheet.tsx
  src/hooks/useBottomSheet.ts
Labels: feat

#60 지도뷰 공간리스트 마커 찍기 구현
  src/components/nearby-place/Map.tsx
  src/pages/nearby-place/[[...station]].tsx
Labels: feat

#64 공간 상세 뷰 지도 현재 위치로 부드럽게 이동
  src/components/detail/location/Map.tsx
Labels: refactor

#61 Feat/#56 공간 리스트 이미지 스켈레톤 UI 추가
  src/components/list/PlaceItem.tsx
  src/components/list/PlaceList.tsx
  src/components/list/Skeleton.tsx
  src/hooks/useStationSearch.ts
  src/services/detail/types.tsx
  src/services/index.ts
  src/services/list/index.tsx
Labels: chore, feat

#66 [Fix] 홈화면에서 주변장소 찾기로 들어갈 경우 마커가 안 뜨는 오류 해결
  src/components/nearby-place/BottomSheet.tsx
  src/components/nearby-place/Map.tsx
  src/hooks/useBottomSheet.ts
  src/pages/nearby-place/[[...station]].tsx
Labels: fix

#68 공간 상세 뷰 와이파이 정보
  src/components/detail/PlaceDetailInfo.tsx
  src/components/detail/imageCarousel.tsx
  src/components/detail/placeDetailNav/FacilityInformation.tsx
  src/components/detail/placeInfo.tsx
  src/pages/detail/[id].tsx
Labels: fix

#73 온보딩 1차 QA
  src/components/onboarding/Onboarding.tsx
Labels: chore

#75 결과없음 페이지 1차 QA
  src/components/list/PlaceList.tsx
Labels: chore

#77 공간 상세 뷰 1차 QA
  src/assets/icons/kakaoTalk_logo.svg
  src/components/common/detail/DetailInformationTextBox.tsx
  src/components/detail/DetailNavigator.tsx
  src/components/detail/PlaceDetailInfo.tsx
  src/components/detail/ShareModal.tsx
  src/components/detail/imageCarousel.tsx
  src/components/detail/location/Map.tsx
  src/components/detail/placeDetailNav/BookingButton.tsx
  src/components/detail/placeDetailNav/FacilityInformation.tsx
  src/components/detail/placeDetailNav/Map.tsx
  src/components/detail/placeDetailNav/OperatingTime.tsx
  src/components/detail/placeDetailNav/PlaceIntroduce.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
  src/components/detail/placeInfo.tsx
  src/pages/detail/[id]/location.tsx
Labels: fix

#80 [Fix] 상세주소 포함 시 마커 안 찍히는 오류 수정
  src/components/nearby-place/Map.tsx
Labels: fix

#78 Feat/#70 공간 리스트뷰, 지하철역 검색뷰, 상세뷰 1차 QA
  src/components/common/Layout.tsx
  src/components/common/Toast.tsx
  src/components/detail/ShareModal.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
  src/components/list/PlaceItem.tsx
  src/components/list/PlaceList.tsx
  src/components/list/Skeleton.tsx
  src/context/ToastContext.tsx
  src/hooks/useNavigation.ts
  src/hooks/useStationSearch.ts
  src/hooks/useToast.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/detail/[id].tsx
  src/pages/detail/[id]/location.tsx
  src/pages/list/index.tsx
  src/pages/nearby-place/[[...station]].tsx
  src/pages/search/index.tsx
  src/styles/globals.css
Labels: fix

#82 [Fix] 공간 상세 뷰 지도 상하 스크롤 막기
  src/components/detail/location/Map.tsx
Labels: fix

#84 [Fix]사파리에서 margin bottom 적용 안되는 문제 해결
  src/components/detail/placeDetailNav/BookingButton.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
Labels: fix

#86 북마크 기능 주석처리
  src/components/detail/ShareModal.tsx
  src/components/detail/placeInfo.tsx
Labels: chore
