Repository WOK-AT/WOKAT_CLIENT, pull requests merged in 2023-07, with the labels that each got.

#91 [Fix] 내주변 장소 찾기 지도 겹치는 오류 수정
  src/components/nearby-place/Map.tsx
Labels: fix

#92 공간 상세 뷰 2차 QA
  src/components/detail/DetailNavigator.tsx
  src/components/detail/PlaceDetailInfo.tsx
  src/components/detail/location/Map.tsx
  src/pages/detail/[id]/index.tsx
  src/pages/detail/[id]/location.tsx
Labels: fix, refactor

#96 Feat/#93 QA 및 기타 수정
  src/components/WokatSEO.tsx
  src/components/common/Header.tsx
  src/components/list/PlaceItem.tsx
  src/styles/globals.css
Labels: chore

#98 [Chore] 공간 상세 뷰 distance API 수정
  src/components/detail/PlaceDetailInfo.tsx
  src/components/detail/imageCarousel.tsx
  src/components/detail/placeInfo.tsx
  src/components/list/PlaceItem.tsx
  src/components/list/PlaceList.tsx
  src/hooks/queries/useDetail.ts
  src/services/detail/index.tsx
  src/services/detail/types.tsx
Labels: chore

#101 [Feat] 홈 화면 추가 아이콘
  public/app_icon.png
  src/components/WokatSEO.tsx
  src/pages/_document.tsx
Labels: feat

#103 [Fix] 주변장소찾기 마이페이지 헤더 아이콘 삭제
  src/pages/nearby-place/[[...station]].tsx
Labels: fix

#105 Feat/#99 3차 QA 및 사용성 개선
  next.config.js
  public/og_thumbnail.webp
  public/thumbnail.png
  src/assets/images/background.svg
  src/assets/images/background.webp
  src/assets/images/block.svg
  src/assets/images/block.webp
  src/assets/images/onboarding_1.avif
  src/assets/images/onboarding_1.webp
  src/assets/images/onboarding_2.avif
  src/assets/images/onboarding_2.webp
  src/assets/images/onboarding_3.avif
  src/assets/images/onboarding_3.webp
  src/assets/images/onboarding_4.avif
  src/assets/images/onboarding_4.webp
  src/assets/images/onboarding_5.avif
  src/assets/images/onboarding_5.webp
  src/components/WokatSEO.tsx
  src/components/common/ImageFallback.tsx
  src/components/common/Loading.tsx
  src/components/list/EmptyList.tsx
  src/components/list/FAB.tsx
  src/components/list/PlaceItem.tsx
  src/components/list/PlaceList.tsx
  src/components/nearby-place/BottomSheet.tsx
  src/components/onboarding/Onboarding.tsx
  src/hooks/queries/usePlaceList.ts
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/list/index.tsx
  src/services/list/types.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: fix, chore, feat

#106 공간 상세뷰 3차 QA
  src/assets/icons/spot.svg
  src/assets/images/default_place.svg
  src/components/detail/ImageCarousel.tsx
  src/components/detail/PlaceImage.tsx
  src/components/detail/PlaceInfo.tsx
  src/components/detail/placeDetailNav/PlaceIntroduce.tsx
  src/pages/detail/[id]/index.tsx
Labels: fix, chore

#108 Feat/#99 3차 QA 및 사용성 개선 + 추가 QA 반영
  src/components/list/PlaceItem.tsx
  src/pages/list/index.tsx
Labels: fix

#111 Feat/#99 Suspense 에러 해결
  package.json
  src/assets/icons/info.svg
  src/assets/lottie/Spinner.json
  src/components/WokatSEO.tsx
  src/components/detail/PlaceInfo.tsx
  src/components/detail/ShareModal.tsx
  src/components/list/Message.tsx
  src/components/nearby-place/BottomSheet.tsx
  src/components/nearby-place/Spinner.tsx
  src/hooks/queries/usePlaceList.ts
  src/hooks/useNavigation.ts
  src/pages/_app.tsx
  src/pages/detail/[id]/index.tsx
  src/pages/index.tsx
  src/pages/list/index.tsx
  src/pages/nearby-place/[[...station]].tsx
  src/services/detail/index.tsx
  src/services/detail/types.tsx
  src/utils/disableScroll.ts
  yarn.lock
Labels: fix

#112 공간 상세 뷰 5차 QA
  src/assets/icons/bookingTag.svg
  src/assets/icons/facilityInformation.svg
  src/assets/icons/kakaoTalk_logo.svg
  src/assets/icons/operatingTime.svg
  src/assets/icons/placeLocation.svg
  src/assets/images/default_place.svg
  src/assets/images/default_place.webp
  src/components/common/detail/DetailInformationTitle.tsx
  src/components/detail/DetailNavigator.tsx
  src/components/detail/PlaceDetailInfo.tsx
  src/components/detail/PlaceInfo.tsx
  src/components/detail/placeDetailNav/BookingButton.tsx
  src/components/detail/placeDetailNav/FacilityInformation.tsx
  src/components/detail/placeDetailNav/OperatingTime.tsx
  src/components/detail/placeDetailNav/PlaceIntroduce.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
  src/pages/detail/[id]/index.tsx
  src/types/information.ts
Labels: fix, chore

#115 [Fix] 공간 상세 뷰 스크롤
  src/components/detail/DetailNavigator.tsx
Labels: fix

#117 [Chore]공간 상세 뷰 사파리 아이콘 교체
  src/assets/icons/elec.svg
  src/assets/icons/hdmi.svg
  src/assets/icons/parking.svg
  src/assets/icons/person.svg
Labels: chore

#119 공간 상세 뷰 정보 없는 열 안보이게 처리
  src/components/common/detail/DetailInformationTextBox.tsx
  src/components/detail/PlaceDetailInfo.tsx
  src/components/detail/PlaceImage.tsx
  src/components/detail/placeDetailNav/BookingButton.tsx
  src/components/detail/placeDetailNav/FacilityInformation.tsx
  src/components/detail/placeDetailNav/OperatingTime.tsx
  src/components/detail/placeDetailNav/PlaceIntroduce.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
Labels: chore, feat

#120 Feat/#113 카카오톡 메시지 공유 템플릿 수정 및 스크롤, 여백 수정
  src/components/detail/PlaceInfo.tsx
  src/components/list/PlaceList.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: fix

#123 공간 상세 뷰 height 지정
  src/pages/detail/[id]/index.tsx
Labels: chore, feat

#124 [Chore] google analytics 코드 삽입
  src/components/GAScript.tsx
  src/pages/_app.tsx
Labels: chore

#126 [Chore] Google Tag Manager 코드 삽입
  src/components/GAScript.tsx
  src/pages/_document.tsx
Labels: chore

#127 워캣 피드백 버튼
  src/assets/icons/feedback.svg
  src/assets/icons/feedbackInfoText.svg
  src/components/common/FeedbackButton.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
Labels: feat

#130 [Chore] Google Tag Manager id 설정
  src/components/GAScript.tsx
  src/pages/_document.tsx
Labels: fix, chore

#132 [Chore] 피드백 메시지 아이콘 object tag로 변경
  src/components/common/FeedbackButton.tsx
Labels: chore
