Repository WOK-AT/WOKAT_CLIENT, pull requests merged in 2023-08, with the labels that each got.

#135 chore/#134: 페이지별 GTM id 추가
  src/components/list/FAB.tsx
  src/components/list/PlaceItem.tsx
  src/components/list/PlaceList.tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: chore

#136 chore : 공간 상세 뷰 GTM ID 추가
  src/components/common/Modal.tsx
  src/components/detail/PlaceInfo.tsx
  src/components/detail/ShareModal.tsx
  src/components/detail/placeDetailNav/PlaceLocation.tsx
  src/pages/detail/[id]/location.tsx
Labels: chore

#137 fix : 모달 취소버튼 위치 수정
  src/components/common/Modal.tsx
Labels: fix

#139 HOTFIX: 리스트 이미지 크기 오류 해결
  src/components/list/PlaceItem.tsx
Labels: fix, chore
